### ISSUE TITLE
Venomous Snakes Can't Attack While Crouched

### ISSUE THREAD

**Issue by LethalPlacebo** [cipherxof/MGS3CrouchWalk#1]
If you crouch walk by a venomous snake, it will raise up and hiss and attempt to attack you, but it can't. Its hissing sound will bug out and replay over and over very quickly. Standing up or laying down fixes the issue, and the snake will either immediately attack you or lay back down, depending on your distance.

**Comment by cipherxof** [comment]
This has been fixed in 0.2.0.
