### ISSUE TITLE
Latest Release Seems Very Bugged

### ISSUE THREAD

**Issue by LethalPlacebo** [cipherxof/MGS3CrouchWalk#2]
Downloaded the latest release of the mod, tried both the version here on Github as well as the NexusMods version. I updated from the previous version, but when I found certain things weren't working I restored my original assets folder (I made a backup) and reinstalled the mod again:

What works
-variable crouch walking speeds
-grass rustling sounds when crouch walking through it

What does not work / is bugged
-crouch walking itself still does not make any sound, at any speed
-crouch walking at full speed behind a guard still does not alert them
-when slow crouch walking, either with the d-pad or the analog stick, sometimes a random sound effect will start to play and loop. Sometimes it's a gunshot. Sometimes it's an engine whirring up (I think the ones from the flying platforms). Very weird

**Comment by cipherxof** [comment]
Can you please try with 0.2.1?

**Comment by LethalPlacebo** [comment]
Hello, can confirm that the bugs seem to be fixed with 0.2.1! Both crouch walk speeds have sounds now, crouch walking at full speed behind a guard now alerts them, while the slow speed does not, and I could not replicate the strange sounds playing while slow crouch walking anymore. Nice work! I will close this issue now.
