### ISSUE TITLE
Can't move while weapon ist equipped

### ISSUE THREAD

**Issue by err0r2k** [cipherxof/MGS3CrouchWalk#8]
When Snake is crouching and a weapon ist equipped, he can't move.

**Comment by cipherxof** [comment]
make sure to copy all of the files to your game folder.

**Comment by err0r2k** [comment]
I downloaded the package again and copied everything into the MGS3 root folder.

It is still not working but I tried different MGS Versions and languages and I found out:

- Europe Version - German = Not working
- Europe Version - English = Working
- US Version - English = Working

Someone mentioned in #4 that the german folder is missing. I checked the package and he is right. This seems the problem when you play the Europe Version with German language. 
Would it be possible to fix this please?

Thank you!

**Comment by cipherxof** [comment]
> I downloaded the package again and copied everything into the MGS3 root folder.
> 
> It is still not working but I tried different MGS Versions and languages and I found out:
> 
> * Europe Version - German = Not working
> * Europe Version - English = Working
> * US Version - English = Working
> 
> Someone mentioned in #4 that the german folder is missing. I checked the package and he is right. This seems the problem when you play the Europe Version with German language. Would it be possible to fix this please?
> 
> Thank you!

I think you should be able to rename the `fr` or `jp` folder to `de` and it should work.

**Comment by err0r2k** [comment]
I renamed `fr` to `gr` and it worked. Thank you!
Do you know what the .mtar files do? Because the number of files in each folder are different.

**Comment by cipherxof** [comment]
> I renamed `fr` to `gr` and it worked. Thank you! Do you know what the .mtar files do? Because the number of files in each folder are different.

Awesome, we’ll just include the gr folder in the next release. 

mtars are the animation motion archives.

**Comment by henzla** [comment]
> > I renamed `fr` to `gr` and it worked. Thank you! Do you know what the .mtar files do? Because the number of files in each folder are different.
> 
> Awesome, we’ll just include the gr folder in the next release.
> 
> mtars are the animation motion archives.

Hey my friend, I have the same problem like @err0r2k, i already tried to rename "fr" or "jp" folder to "de" or "gr" but its still not working, I cant move while weapon equipped. Would love to play the game with the mod, can you help me or release a fix for hat? Would highly appreciate
